### ISSUE TITLE
allow compiler-options :output-to and :output-dir as default

### ISSUE THREAD

**Issue by thos37** [boot-clj/boot-cljs#104]
In #75 @Deraen wrote: "You should not try to set :output-to or :output-dir using compiler-options in boot-cljs, they are set automatically (you can override them, but it probably wont work)."

This method of only using files in the filesystem to configure compiler options seems counter-intuitive and very non-idiomatic. It took me a while to figure out why (cljs :compiler-options { :output-to "path/to/public/js/main.js" }) was being ignored, and I'm sure others have had the same problem. I think it's inappropriate to prevent the use of compiler options unless a build.boot user explicitly chooses to do this. I see the rationale of having multiple builds as an option, but not at the expense of direct access to the compiler options. This also hinders usage of boot by developers coming from lein and cljs build scripts who expect to be able to set these options in the build file. Can we default to allowing to set the compiler's options from within build.boot and only overriding them when someone explicitly creates a main.cljs.edn file, maybe even with a flag in the boot-cljs task that enables the user to choose between the two?

**Comment by Deraen** [comment]
In fact using files for configuration **is** idiomatic and preferred way with Boot.

The problem with setting output-to and output-dir is that you don't know the directory yourself (Boot temporary direction) so what would you set the options to? Directly setting the options to target-path (`target/something`) would completely skip Boot filesets and break Boot-reload and all other tasks which depend on JS files from Boot-cljs being available on fileset and classpath (Ring resource middleware).

**Comment by martinklepsch** [comment]
While it is idiomatic in Boot it still is confusing to new users if these options are just ignored. 

If the paths given to the compiler would be relative to a "target dir" we could easily support it but I think they are not. 

Suggestion: we detect when users pass these options and fail with an informative message with a link somewhere where it's explained why using files to configured this kind of stuff is very handy in boot. 
Potentially we could even ask the user if he wants us to create a cljs.edn file for him based on some guesswork from the options they provided.

**Comment by Deraen** [comment]
Warning about overwriting the options is good idea.

Relative paths could work, but I don't want to do any special handling for compiler-options. Options passed to `compiler-options` should work exactly the same as with Cljs, unless they are overwritten/ignored.

It would be possible to provide task `output` option which would set `output-to` and `output-dir` compiler-options to relative path within fileset, but I don't want to add new options unless they are necessary as any new options make the implementation more complex.

If no `.cljs.edn` file exists, we are currently generating default file and this will print a line: https://github.com/adzerk-oss/boot-cljs/blob/master/src/adzerk/boot_cljs.clj#L141 The message could be improved.

**Comment by thos37** [comment]
Mmm, I see now why using files is related to how Boot handles isolated temp filesets.  @Deraen I like the auto-generated .cljs.edn and I think the "output" option would address my issue.  Maybe the cljs.edn auto-gen could throw an error if the requested output-dir is not relative?  I looked at the boot-cljs repl doc and saw nothing about how to set the output location, so I figured I'd just do it in the compiler-options.  All I wanted was to be able to set the output directory to some arbitrary deeply nested place within the target path (because my html index.html was deeply nested.)  Having to recreate this target structure within my src/cljs folder seems strange.  

One thing I noticed about the autogenerated cljs.edn is that it automatically creates a :require[] of my cljs files.  But by creating a cljs.edn somewhere else, I now have to manually keep that vector updated.  I really don't want to have to update that file every time I add a new file.  Maybe this is necessary when you have multiple different builds, but often not with just one.  So I think what I'm wanting is to be able to have configurable control over what boot-cljs does from the build.boot config and/or command line.

**Comment by Deraen** [comment]
@thos37 You don't need to require all the files, it's even preferred that you only require one file, a main namespace, which then requires other namespaces as usual.

**Comment by martinklepsch** [comment]
> All I wanted was to be able to set the output directory to some arbitrary deeply nested place within the target path (because my html index.html was deeply nested.) Having to recreate this target structure within my src/cljs folder seems strange.

You could solve this problem slightly differently by using the `sift` task. (`boot sift -h`)

**Comment by anthgur** [comment]
Is there an update on this? `sift` doesn't seem like a very stable solution. fwiw I think picking up on `compiler-options` and outputting relative to the target dir makes sense. That's the first thing I tried and it seems natural.

This is pretty necessary if you want to for example serve static assets out of a specific resources directory (ex. `public`).

**Comment by Deraen** [comment]
@anthgur It's already possible to serve static assets out of a certain classpath prefix, like `public`. You need to move your `cljs.edn` file to the same prefix in fileset and set `:asset-path` option for boot-cljs and boot-reload. Not optimal, but it is possible.

**Comment by anthgur** [comment]
@Deraen that makes sense, I misunderstood how `cljs.edn` file paths interact with the task. It might be worth adding to/clarifying in the readme as it's likely a common use case. The section on [multiple builds](https://github.com/adzerk-oss/boot-cljs#multiple-builds) hints at this but it wasn't clear to me. Thanks!

**Comment by Deraen** [comment]
I have now implemented warnings if user set compiler-options are replaced: https://github.com/adzerk-oss/boot-cljs/commit/dc73bd26c7531ab768e92b7a4202ce2e6c7dea38

I'm still suspicious about need to introduce new options to allow setting output-to from build.boot. While there are some problems with current cljs.edn approach (asset-path), I think it quite good. It is already used by other tasks (boot-cljs-test) to create new cljs builds and so on.

**Comment by jeaye** [comment]
Having to `mkdir src/js/js` and put in an edn file to get `js/main.js` output is bonkers and terribly unapproachable. I'm not familiar with the intricacies of boot-cljs, but it shouldn't be expected that I am; what should be expected is some sane level of configuration, preferably within clojure and not the filesystem.

**Comment by micha** [comment]
@jeaye The .cljs.edn file approach has one huge advantage over direct configuration of the task: it's open, where the task options are closed. For example, other tasks can find .cljs.edn files in the fileset and modify them, regardless of what will eventually be used to compile the final javascript. Manipulating task options, on the other hand, couples tasks in a way that quickly results in spaghetti code, because now all tasks need to know about all the other tasks that are in the pipeline. This is something we've worked hard to avoid in boot, and it's paid off handsomely so far.

**Comment by micha** [comment]
One thing to consider is having a task that generates your .cljs.edn files, which is the way I do it anyway. I have a task that automatically generates the html files and their corresponding cljs.edn files, so I don't need to mess with that boilerplate myself. The actual location of the compiled js is an implementation detail that I don't need to deal with because it's taken care of by my boot task.

**Comment by thos37** [comment]
@micha would you mind sharing your .cljs.edn boot task?  I think it would help to include that kind of example in the docs.  Also, what if in the absence of a .cljs.edn file, the boot-cljs task would honor the cljs compiler settings for its location and create it there?  I think it's great that boot-cljs allows the flexibility of the .cljs.edn file approach, but it would be great if it would fall back to the compiler settings, which I see as the de facto approach that crosses tooling divides.

**Comment by thos37** [comment]
@micha  Your points about the complexities of the cljs compiler options make sense.  

It would probably help if the Options section of the [Usage wiki](https://github.com/adzerk-oss/boot-cljs/wiki/Usage) were more emphatic and explicit about how the compiler options are overridden, especially because it even links to the Clojurescript compiler options wiki without describing boot-cljs's exceptions.

**Comment by thos37** [comment]
I added the following to the usage wiki.  Is this accurate?

Note that the CLJS compiler's `:output-to` and `:output-dir` options will be overridden by the `cljs` task.  These options are determined by the name and location of a `.cljs.edn`.  By default the `cljs` task will automatically create a `main.cljs.edn` file in the root of the fileset, which will result in a `main.js` in the root of the output directory.

**Comment by mobileink** [comment]
see https://github.com/boot-clj/boot-cljs/pull/155
