### ISSUE TITLE
println output to javascript console instead of the repl

### ISSUE THREAD

**Issue by sonwh98** [boot-clj/boot-cljs#120]
sometimes I dont want to start the repl. when the repl is not connected, println should show up in the js console but that is not the case.  How can this be configured?

**Comment by Deraen** [comment]
Are you already calling `enable-console-print!` somewhere: https://github.com/cljsinfo/cljs-api-docs/blob/catalog/refs/cljs.core/enable-console-printBANG.md ?

**Comment by Deraen** [comment]
Maybe this has been fixed by boot-cljs-repl 0.3.3 (https://github.com/adzerk-oss/boot-cljs-repl/commit/883a397cdcb1ad04fc50298bb1bfdc49c1ce7db3)?

**Comment by Deraen** [comment]
Closing as some issues related to this have been fixed at boot-cljs-repl.
