### ISSUE TITLE
A boot-cljs default

### ISSUE THREAD

**Issue by learningcljs** [boot-clj/boot-cljs#125]
From [tutorial 5 of moder-cljs](https://github.com/magomimmo/modern-cljs/blob/8ce9538f0b038ba98357cd8f9eddf73896cd48bf/doc/second-edition/tutorial-05.md):

> NOTE 4: this an incidental complexity produced by the boot-cljs task. Do you remember when at the beginning of this series I wrote about the idiosyncrasies of the building tools when you walk a little bit out of its defaults? This is one them. Here you have to choose between two alternatives: either you adhere to the very widespread convention of keeping the js resources confined in a js subdirectory of the directory where your html pages live; or, to not incur the above incidental complexity, you stay with the defaults of boot-cljs task and abandon an almost universal convention of the web.

Could this note help improve this specific default behavior in boot-cljs?

**Comment by martinklepsch** [comment]
I think we would all like this to be less confusing but the truth is that the path munging and the various options affecting it have become quite complex and people have many different requirements. 

There could be some particular "modes" like
- I want to serve my js from within a JS directory
- I want a public directory at the root of my classpath
and so on... but so far I think most people just set things up and forget about them. :)

**Comment by Deraen** [comment]
With the latest version, `:output-to`, `:output-dir` and `:asset-path` can be configured manually. This should allow using any configuration.
