### ISSUE TITLE
Task for generating edn files

### ISSUE THREAD

**Issue by flyboarder** [boot-clj/boot-cljs#141]
I would be nice if there was such a task within the cljs package itself, here is my attempt:
```clojure
(boot/deftask cljs-edn
  "Generate a .cljs.edn file."
  [e edn      VAL str   "EDN file name."
   i init-fn  VAL sym   "EDN init function."
   r require  VAL [sym] "Vector of namespaces to require."
   f init-fns VAL [sym] "Vector of fuctions to wrap in do block."
   t target   VAL kw    "Target platform."
   d closure-defines  VAL {} "A map of closure defines options."
   o compiler-options VAL {} "A map of compiler options."]
   (assert (:edn *opts*) "Must provide an edn file name.")
   (assert (:init-fn *opts*) "Must provide an init-fn.")
   (let [edn    (:edn *opts*)
         init   (:init-fn *opts*)
         main   (symbol (namespace init))
         ednstr {:require (:require *opts* [main])
                 :init-fns (:init-fns *opts* [init])
                 :compiler-options (:compiler-options *opts*
                                     {:target (:target *opts*)
                                      :closure-defines (:closure-defines *opts*)})}
         tmp    (boot/tmp-dir!)
         fname  (str edn ".cljs.edn")
         fedn   (io/file tmp fname)]
     (boot/with-pre-wrap fileset
       (util/info (str "Generating EDN file: " fname "\n"))
       (doto fedn (spit ednstr))
       (-> fileset (boot/add-resource tmp) boot/commit!))))
```

**Comment by martinklepsch** [comment]
This is good idea I think :)

- Why are there separate options for init-fn and init-fns? Seems this could
be one?
- I wonder if we could use somehow use this to east the setting of
asset-path which is previously confused many

**Comment by flyboarder** [comment]
@martinklepsch init-fn is an easy option which will extract the ns and populate require for you, init-fns overrides that portion of the edn file. Essentially one version is automatic and the other is manual.

**Comment by martinklepsch** [comment]
Ah cool that sounds great 👍

**Comment by Deraen** [comment]
Boot-cljs already adds require to any namespace in `:init-fns` so duplicating that logic here is unnecessary: https://github.com/adzerk-oss/boot-cljs/blob/master/src/adzerk/boot_cljs/middleware.clj#L68

**Comment by flyboarder** [comment]
@Deraen @martinklepsch created PR https://github.com/adzerk-oss/boot-cljs/pull/142

**Comment by mobileink** [comment]
what problem does this solve? why is parameterizing a task like this better than just writing the edn file?

**Comment by flyboarder** [comment]
@mobileink there are lots of cases where I would like to generate an entry-point as part of a build. Usually for frameworks like express/feathers.js when generating server files or for cases where I am using boot for things other than building projects, like project management tasks which generate project files, etc.

**Comment by Deraen** [comment]
This is no longer a goal. All the options can now be provided as task options with the latest release. Using Boot-cljs without .cljs.edn can still be problematic (and slow) as in this case all the .cljs files in fileset will be compiled, but I have some ideas on how to fix that eventually: https://github.com/boot-clj/boot-cljs/issues/169
