### ISSUE TITLE
Gracefully handle symbols in .cljs.edn files

### ISSUE THREAD

**Issue by arichiardi** [boot-clj/boot-cljs#148]
At the moment, an exception is thrown when I use:

```
{:require [rest-resource-viz.core]
 :on-jsload 'rest-resource-viz.core/on-jsload} ;; with apex
```

Instead of the correct:

```
{:require [rest-resource-viz.core]
 :on-jsload rest-resource-viz.core/on-jsload}
```

It would be great to walk the edn file and warn instead. I know this opens the door to a bigger problem, that is how to validate `.cljs.edn` files but ... well... at some point maybe we need it.

Thanks for moving it to the new org @Deraen!

**Comment by Deraen** [comment]
Done in https://github.com/boot-clj/boot-cljs/commit/fbf5297787dee1aeb2eb92edcb2ac537e67f2bfc

Boot-reload should do the same for `:on-jsload` option: https://github.com/adzerk-oss/boot-reload/issues/116
