### ISSUE TITLE
Default asset-path should respect .cljs.edn position

### ISSUE THREAD

**Issue by arichiardi** [boot-clj/boot-cljs#152]
Hi Deraen,

I was fiddling with [a `boot-figreload` bug](https://github.com/boot-clj/boot-figreload/issues/3) and noticed that when you don't explicitely specify the `:asset-path` option, `boot-cljs` calls [`get-name`](https://github.com/boot-clj/boot-cljs/blob/311709dd5f99eb09ee3469ea4995b5a066293429/src/adzerk/boot_cljs/middleware.clj#L59) for figuring out which `asset-path` to use.

Unless I am doing something wrong, it should respect the position where you put the `.cljs.edn` file I guess.

EDIT: I have a repro here: https://github.com/arichiardi/figreload-demo/tree/boot-cljs-152

**Comment by Deraen** [comment]
Aha, interesting, I thought it would use `getPath`.

**Comment by Deraen** [comment]
Fixes in #156
