### ISSUE TITLE
Add support to load foreign-libs from remote url in deps.cljs files

### ISSUE THREAD

**Issue by nathandao** [boot-clj/boot-cljs#158]
Seems like boot-cljs only supports local files for  `:foreign-libs`. Would be great if that also works for remote urls - which is the case for ClojureScript compiler options: https://github.com/clojure/clojurescript/wiki/Compiler-Options#foreign-libs

[`boot-cljs.clj` #L50](https://github.com/boot-clj/boot-cljs/blob/3239122ccceab87320c6b963e32f00477b508b2d/src/adzerk/boot_cljs.clj#L50):

```
(defn- read-cljs-edn
  [tmp-file]
  (let [file (core/tmp-file tmp-file)
        path (core/tmp-path tmp-file)]
    (assoc (read-string (slurp file))
           :path     (.getPath file)
           :rel-path path
           :id       (string/replace (.getName file) #"\.cljs\.edn$" ""))))
```

**Comment by Deraen** [comment]
The included code snippet doesn't have anything to do with deps.cljs or foreign-libs handling?

Nothing in Boot-cljs should affect this, and I have validated that this works both Boot-cljs and bare Cljs:

```
:foreign-libs [{:provides ["cljsjs.react"]
                :file "https://cdnjs.cloudflare.com/ajax/libs/react/15.4.2/react.js"}
               {:provides ["cljsjs.react.dom"]
                :requires ["cljsjs.react"]
                :file "https://cdnjs.cloudflare.com/ajax/libs/react/15.4.2/react-dom.js"}]
```

Cljs 1.9.495 (this feature is broken at least in 456).

Reagent dep with cljsjs/react and cljsjs/react-dom exclusion.

**Comment by nathandao** [comment]
sorry about this - clearly screwed up my issue report ._.

Turned out to be an [existing ClojureScript issue](http://dev.clojure.org/jira/browse/CLJS-1009?page=com.atlassian.jira.plugin.system.issuetabpanels:all-tabpanel#issue-tabs) - which happens when defining `:foreign-libs` in `deps.cljs` files.
