### ISSUE TITLE
Can't compile for Node.js & require native modules

### ISSUE THREAD

**Issue by anmonteiro** [boot-clj/boot-cljs#175]
Because new CLJS adds native node modules to the compiler env when target is Node, this line is now incorrect.

https://github.com/boot-clj/boot-cljs/blob/master/src/adzerk/boot_cljs/impl.clj#L17

see https://github.com/clojure/clojurescript/blob/998933f5090254611b46a2b86626fb17cabc994a/src/main/clojure/cljs/env.cljc#L59

**Comment by Deraen** [comment]
What is incorrect? We need to also pass in options?
