### ISSUE TITLE
Output non-serializable exception from boot-cljs

### ISSUE THREAD

**Issue by sparkofreason** [boot-clj/boot-cljs#182]
Boot requires that exceptions be serialized to pass between tasks. However, when exceptions are thrown during CLJS compilation (e.g. from a macro) are effectively swallowed if they contain non-serializable data. This occurs frequently if using macros that work with clojure.spec objects, some of which cannot be serialized. Suggested work-around is to output the offending exception if non-serializable, so at least some information is presented as to root cause.

**Comment by Deraen** [comment]
Related: https://github.com/boot-clj/boot-cljs/pull/181

**Comment by Deraen** [comment]
Should be fixed in 2.1.5
