### ISSUE TITLE
Unclear interaction between Boot reload, Boot cljs and ring.middleware.resource

### ISSUE THREAD

**Issue by giorgio-v** [boot-clj/boot-cljs#82]
First of all, I don’t know if it’s the right place to open an issue. Maybe, the boot-reload repo would be a better place? If so, let me know.

I’d like to keep my web assets under `resources/public` and serve them via `ring.middleware.resource`. To achieve that, I should put the ClojureScript compilation under the same dir. So far, so good. 

But, in this way it seems that I end up reloading the page because `boot-reload` sees the compiled JS as changed.

Is there a way out this?

**Comment by Deraen** [comment]
You shouldn't try to serve files JS from the filesystem. The compiled fires are already accessible through classpath so you just need to add proper resource middleware to serve them.

https://github.com/Deraen/saapas and https://github.com/martinklepsch/tenzing should provide example of proper configuration.

**Comment by martinklepsch** [comment]
Maybe it's boot-reload's [asset-path](https://github.com/adzerk-oss/boot-reload/blob/master/src/adzerk/boot_reload.clj#L79) option that could help here?

**Comment by giorgio-v** [comment]
If I undertand the docs correctly that would help if you need to watch a certain path. I mean, yes, if I’d put the assets under `public` I would have to set `asset-path` as well but I’d still have the endless reload problem.

**Comment by Deraen** [comment]
Asset-path won't help if you have e.g. your target path set to `resources/public` and resources-path as `resources`, which is how I understand the first post.
