### ISSUE TITLE
Document :asset-path

### ISSUE THREAD

**Issue by martinklepsch** [boot-clj/boot-cljs#94]
The `:asset-path` option that can be used via `.cljs.edn` files is not really documented in the Readme or task docstring.

**Comment by Deraen** [comment]
"It should not be used"...

We should instead provide out own option which would work consistently across boot tasks which require such option. Could be named `:web-root`. @micha has loads of ideas for this and I do not yet grok what would be the best way to implement this.

Until we have proper solution I would accept mention on the the docs.

**Comment by micha** [comment]
:+1:

**Comment by jeluard** [comment]
If `:asset-path` (and `:output-*`?) are not supposed to be used and do not work could we make `boot-cljs` throw some error when they are specified?

**Comment by Deraen** [comment]
Sorry for confusion. Currently `:asset-path` has to be used. Hopefully in future we can replace asset-path option with something which works consistently between all tasks.

**Comment by ethagnawl** [comment]
I'm getting tripped up here as well.

Is it possible to use an edn file modeled on [this](https://github.com/Deraen/saapas/blob/master/src/cljs/js/main.cljs.edn) one to have my cljs output to target/public/js/main.js instead of target/js/main.js?

**Comment by timothypratley** [comment]
@ethagnawl Did you find a solution? I'd like to have a public directory too :)

**Comment by ethagnawl** [comment]
@timothypratley Unfortunately, I did not.

**Comment by akmiller78** [comment]
Is there still no solution to this? Per above, I'd like to have my js under a public folder as well as I have other items in resources I don't want public. If I move forward without a public directory then I'd have to manually control access to each folder instead of allowing access to everything in the public folder.

**Comment by Deraen** [comment]
I think we used to have our own `:asset-path` long ago. Now we just use the `:asset-path` compiler-option which should work the same as everywhere. (Boot-reload still has it's own options, but hopefully I'll get to simplifying that some time soon.)

With latest release `:output-to` and `:output-dir` can also be set manually.
